# Etapa de construcción
FROM node:20-alpine AS builder

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

RUN npm install

# Copiar todo el resto del proyecto
COPY . .

# Build de Vite
RUN npm run build

# Etapa de Nginx para servir el frontend
FROM nginx:alpine

# Copiar los archivos construidos a Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
